export const STORE_USER = "STORE_USER";
export const REMOVE_USER = "REMOVE_USER";

//Areas
export const FETCH_AREAS_REQUEST = "FETCH_AREAS_REQUEST";
export const FETCH_AREAS_SUCCESS = "FETCH_AREAS_SUCCESS";
export const FETCH_AREAS_ERROR = "FETCH_AREAS_ERROR";
export const FETCH_AREA = "FETCH_AREA";
export const FETCH_REMOVE_AREA = "FETCH_REMOVE_AREA";

//Questions
export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_RESULT = "FETCH_RESULT";
export const FETCH_COUNTER_QUESTION = "FETCH_COUNTER_QUESTION";
export const FETCH_END_GAME = "FETCH_END_GAME";
export const FETCH_RELOAD_CONFIRMATION = "FETCH_RELOAD_CONFIRMATION";
export const FETCH_RELOAD_NEXT_QUESTIONS = "FETCH_RELOAD_NEXT_QUESTIONS";
export const FETCH_RELOAD_END_GAME = "FETCH_RELOAD_END_GAME";
export const FETCH_RETURN_ON_START_GAME = "FETCH_RETURN_ON_START_GAME";